// src/Dashboard/DownloadDashboard.jsx
import React from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "/Logo1.png"; // from public folder
import { Download } from "lucide-react";

const DownloadDashboard = ({ selectedRow }) => {
  const handleDownload = () => {
    if (!selectedRow) {
      alert("No row selected");
      return;
    }

    const doc = new jsPDF();

    // === HEADER ===
    // Logo (centered)
    doc.addImage(logo, "PNG", 90, 20, 30, 30);

    // Organization Name
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Bihar State Film Development & Finance Corporation (BSFDFC)", 105, 50, { align: "center" });

    // Subheading
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Department of Art & Culture, Govt. of Bihar", 105, 60, { align: "center" });

    // Report Title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Application Details", 105, 75, { align: "center" });

    // === TABLE ===
    const tableData = Object.entries(selectedRow).map(([key, value]) => [
      key,
      value,
    ]);

    autoTable(doc, {
      startY: 85,
      head: [["Field", "Value"]],
      body: tableData,
      styles: { fontSize: 11, cellPadding: 4 },
      headStyles: { fillColor: [128, 0, 0] }, // maroon BSFDFC color
      columnStyles: {
        0: { cellWidth: 60 }, // Field column
        1: { cellWidth: 110 }, // Value column shifted right
      },
    });

    // === FOOTER ===
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by Film Bihar Dashboard", 105, pageHeight - 10, { align: "center" });

    // Save File
    doc.save(`Application_${selectedRow.id || "NOC"}.pdf`);
  };

  return (
   <button
  onClick={handleDownload}
  className="w-10 h-10 bg-gray-100 hover:bg-[#c9e3ff] rounded-full flex items-center justify-center transition-colors duration-200 cursor-pointer"
>
  <Download className="text-gray-600 hover:text-[#0096FF] text-lg transition-colors duration-200" />
  
</button>

  );
};

export default DownloadDashboard;
